import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
  },
  scroll: {
    paddingBottom: 0,
  },
  header: {
    borderBottomWidth: 1,
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  logoMark: {
    alignItems: 'center',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  brand: {
    flex: 1,
    fontSize: 20,
    fontWeight: '800',
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  navPill: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 8,
    paddingVertical: 8,
    width: 82,
  },
  navText: {
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  iconButton: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 36,
    paddingHorizontal: 8,
  },
  languageButton: {
    width: 62,
  },
  squareButton: {
    paddingHorizontal: 0,
    width: 38,
  },
  iconButtonText: {
    fontSize: 12,
    fontWeight: '800',
  },
  menuPanel: {
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 6,
  },
  menuItem: {
    borderRadius: 8,
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  menuItemText: {
    fontSize: 14,
    fontWeight: '700',
  },
  hero: {
    justifyContent: 'flex-end',
    minHeight: 520,
  },
  heroImage: {
    resizeMode: 'cover',
  },
  heroOverlay: {
    backgroundColor: 'rgba(8, 18, 22, 0.56)',
    gap: 16,
    justifyContent: 'center',
    minHeight: 520,
    padding: 24,
  },
  heroTitle: {
    color: '#fff',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 41,
  },
  heroDescription: {
    color: '#edf7f7',
    fontSize: 16,
    lineHeight: 24,
  },
  primaryButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#26a69a',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 20,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
  searchWrap: {
    paddingHorizontal: 16,
    paddingTop: 18,
    zIndex: 3,
  },
  searchBox: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    minHeight: 46,
  },
  searchDropdown: {
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 6,
    overflow: 'hidden',
  },
  searchResult: {
    gap: 4,
    minHeight: 58,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  searchResultTitle: {
    fontSize: 15,
    fontWeight: '800',
  },
  searchResultExcerpt: {
    fontSize: 13,
  },
  searchEmpty: {
    fontSize: 14,
    fontWeight: '700',
    padding: 12,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '900',
    paddingBottom: 14,
    paddingHorizontal: 16,
    paddingTop: 28,
  },
  cardGrid: {
    gap: 14,
    paddingHorizontal: 16,
  },
  postCard: {
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  postImage: {
    height: 170,
    width: '100%',
  },
  postContent: {
    gap: 8,
    padding: 14,
  },
  postTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  postTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
  },
  favoriteButton: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  postExcerpt: {
    fontSize: 14,
    lineHeight: 21,
  },
  readMore: {
    fontSize: 14,
    fontWeight: '800',
    paddingTop: 4,
  },
  form: {
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    marginHorizontal: 16,
    padding: 14,
  },
  input: {
    borderRadius: 8,
    borderWidth: 1,
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  messageInput: {
    minHeight: 110,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  submitButton: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
  },
  submitText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
  notice: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  aboutWrap: {
    gap: 16,
    padding: 16,
  },
  aboutImage: {
    borderRadius: 8,
    height: 230,
    width: '100%',
  },
  aboutPanel: {
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  aboutTitle: {
    fontSize: 25,
    fontWeight: '900',
  },
  aboutSubtitle: {
    fontSize: 19,
    fontWeight: '800',
    paddingTop: 8,
  },
  aboutText: {
    fontSize: 15,
    lineHeight: 23,
  },
  detailWrap: {
    gap: 16,
    padding: 16,
  },
  detailImage: {
    borderRadius: 8,
    height: 240,
    width: '100%',
  },
  carouselDots: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    paddingTop: 10,
  },
  carouselDot: {
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  detailPanel: {
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  detailTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  detailTitle: {
    flex: 1,
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 32,
  },
  detailBody: {
    fontSize: 16,
    lineHeight: 25,
  },
  secondaryButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
  },
  footer: {
    gap: 12,
    marginTop: 30,
    padding: 18,
  },
  footerText: {
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  socialRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  policyRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  policyText: {
    fontSize: 13,
  },
  toast: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    bottom: 18,
    elevation: 5,
    flexDirection: 'row',
    gap: 10,
    left: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'absolute',
    right: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
  },
  toastText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  imagePreviewOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.92)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  imagePreview: {
    height: '82%',
    resizeMode: 'contain',
    width: '100%',
  },
  imagePreviewClose: {
    alignItems: 'center',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    right: 16,
    top: 48,
    width: 44,
    zIndex: 2,
  },
});
